name: PickleQuest
options:
  bundleIdPrefix: tran.io
  deploymentTarget:
    iOS: "18.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 69F6RR9M5J

targets:
  PickleQuest:
    type: application
    platform: iOS
    sources:
      - PickleQuest
    settings:
      base:
        INFOPLIST_FILE: PickleQuest/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: tran.io.PickleQuest
        PRODUCT_NAME: PickleQuest
        MARKETING_VERSION: "0.1.0"
        CURRENT_PROJECT_VERSION: 1
        SWIFT_STRICT_CONCURRENCY: complete
    scheme:
      testTargets:
        - PickleQuestTests

  PickleQuestTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - PickleQuestTests
    dependencies:
      - target: PickleQuest
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: tran.io.PickleQuestTests

  PickleQuestUITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - PickleQuestUITests
    dependencies:
      - target: PickleQuest
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        PRODUCT_BUNDLE_IDENTIFIER: tran.io.PickleQuestUITests
